<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Metalama.Framework" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="XmpCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PointlessWaymarks.SpatialTools\PointlessWaymarks.SpatialTools.csproj" />
  </ItemGroup>

</Project>