<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GeoTimeZone" />
    <PackageReference Include="MathNet.Numerics" />
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" />
    <PackageReference Include="NetTopologySuite.IO.GPX" />
    <PackageReference Include="Unofficial.Garmin.Connect" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PointlessWaymarks.CommonTools\PointlessWaymarks.CommonTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="StateCountyServiceModels\cb_2025_us_county_5m.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="StateCountyServiceModels\OfflineDataNotes.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>